// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
/// options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
static FirebaseOptions get currentPlatform {
if (kIsWeb) {
      return web;
}
switch (defaultTargetPlatform) {
case TargetPlatform.android:
  return android;
case TargetPlatform.macOS:
        return macos;
case TargetPlatform.windows:
        return windows;
case TargetPlatform.linux:
throw UnsupportedError(
'DefaultFirebaseOptions have not been configured for linux - '
'you can reconfigure this by running the FlutterFire CLI again.',
);
default:
throw UnsupportedError(
'DefaultFirebaseOptions are not supported for this platform.',
);
}
}
static const FirebaseOptions android = FirebaseOptions(
apiKey: 'AIzaSyAZBkcePDF9yHBx5PAbL2OI-rkl-Zn9Rf4',
appId: '1:814405376972:android:3e75dcd29e0a05ca999b69',
messagingSenderId: '814405376972',
projectId: 'maddart-ef787',
storageBucket: 'maddart-ef787.appspot.com',
);


static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFuA_DXCOKdCfn4hgyLyTd28qeW8fIfms',
    appId: '1:814405376972:web:b07493ec92a89a20999b69',
    messagingSenderId: '814405376972',
    projectId: 'maddart-ef787',
    authDomain: 'maddart-ef787.firebaseapp.com',
    storageBucket: 'maddart-ef787.appspot.com',
    measurementId: 'G-94HQZFMZDL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWo6TFndI2JKfGrAN9pGMM7FDvUrgAE4w',
    appId: '1:814405376972:ios:800de2a261f0353a999b69',
    messagingSenderId: '814405376972',
    projectId: 'maddart-ef787',
    storageBucket: 'maddart-ef787.appspot.com',
    iosBundleId: 'com.example.rvAdMad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFuA_DXCOKdCfn4hgyLyTd28qeW8fIfms',
    appId: '1:814405376972:web:fcdbebaa37461119999b69',
    messagingSenderId: '814405376972',
    projectId: 'maddart-ef787',
    authDomain: 'maddart-ef787.firebaseapp.com',
    storageBucket: 'maddart-ef787.appspot.com',
    measurementId: 'G-JT0W6X7WMP',
  );

}